//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpWebServices.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ConvertSoap")]
    public interface ConvertSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento inputUnit del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConversion", ReplyAction="*")]
        TpWebServices.ServiceReference1.GetConversionResponse GetConversion(TpWebServices.ServiceReference1.GetConversionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConversion", ReplyAction="*")]
        System.Threading.Tasks.Task<TpWebServices.ServiceReference1.GetConversionResponse> GetConversionAsync(TpWebServices.ServiceReference1.GetConversionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConversionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConversion", Namespace="http://tempuri.org/", Order=0)]
        public TpWebServices.ServiceReference1.GetConversionRequestBody Body;
        
        public GetConversionRequest() {
        }
        
        public GetConversionRequest(TpWebServices.ServiceReference1.GetConversionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConversionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double input;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string inputUnit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string outputUnit;
        
        public GetConversionRequestBody() {
        }
        
        public GetConversionRequestBody(double input, string inputUnit, string outputUnit) {
            this.input = input;
            this.inputUnit = inputUnit;
            this.outputUnit = outputUnit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConversionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetConversionResponse", Namespace="http://tempuri.org/", Order=0)]
        public TpWebServices.ServiceReference1.GetConversionResponseBody Body;
        
        public GetConversionResponse() {
        }
        
        public GetConversionResponse(TpWebServices.ServiceReference1.GetConversionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetConversionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetConversionResult;
        
        public GetConversionResponseBody() {
        }
        
        public GetConversionResponseBody(string GetConversionResult) {
            this.GetConversionResult = GetConversionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConvertSoapChannel : TpWebServices.ServiceReference1.ConvertSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertSoapClient : System.ServiceModel.ClientBase<TpWebServices.ServiceReference1.ConvertSoap>, TpWebServices.ServiceReference1.ConvertSoap {
        
        public ConvertSoapClient() {
        }
        
        public ConvertSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TpWebServices.ServiceReference1.GetConversionResponse TpWebServices.ServiceReference1.ConvertSoap.GetConversion(TpWebServices.ServiceReference1.GetConversionRequest request) {
            return base.Channel.GetConversion(request);
        }
        
        public string GetConversion(double input, string inputUnit, string outputUnit) {
            TpWebServices.ServiceReference1.GetConversionRequest inValue = new TpWebServices.ServiceReference1.GetConversionRequest();
            inValue.Body = new TpWebServices.ServiceReference1.GetConversionRequestBody();
            inValue.Body.input = input;
            inValue.Body.inputUnit = inputUnit;
            inValue.Body.outputUnit = outputUnit;
            TpWebServices.ServiceReference1.GetConversionResponse retVal = ((TpWebServices.ServiceReference1.ConvertSoap)(this)).GetConversion(inValue);
            return retVal.Body.GetConversionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TpWebServices.ServiceReference1.GetConversionResponse> TpWebServices.ServiceReference1.ConvertSoap.GetConversionAsync(TpWebServices.ServiceReference1.GetConversionRequest request) {
            return base.Channel.GetConversionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TpWebServices.ServiceReference1.GetConversionResponse> GetConversionAsync(double input, string inputUnit, string outputUnit) {
            TpWebServices.ServiceReference1.GetConversionRequest inValue = new TpWebServices.ServiceReference1.GetConversionRequest();
            inValue.Body = new TpWebServices.ServiceReference1.GetConversionRequestBody();
            inValue.Body.input = input;
            inValue.Body.inputUnit = inputUnit;
            inValue.Body.outputUnit = outputUnit;
            return ((TpWebServices.ServiceReference1.ConvertSoap)(this)).GetConversionAsync(inValue);
        }
    }
}
