//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaFinal3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getPersonaXMLResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPersonaXML", ReplyAction="*")]
        PracticaFinal3.ServiceReference1.getPersonaXMLResponse getPersonaXML(PracticaFinal3.ServiceReference1.getPersonaXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPersonaXML", ReplyAction="*")]
        System.Threading.Tasks.Task<PracticaFinal3.ServiceReference1.getPersonaXMLResponse> getPersonaXMLAsync(PracticaFinal3.ServiceReference1.getPersonaXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonaXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPersonaXML", Namespace="http://tempuri.org/", Order=0)]
        public PracticaFinal3.ServiceReference1.getPersonaXMLRequestBody Body;
        
        public getPersonaXMLRequest() {
        }
        
        public getPersonaXMLRequest(PracticaFinal3.ServiceReference1.getPersonaXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getPersonaXMLRequestBody {
        
        public getPersonaXMLRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPersonaXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPersonaXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public PracticaFinal3.ServiceReference1.getPersonaXMLResponseBody Body;
        
        public getPersonaXMLResponse() {
        }
        
        public getPersonaXMLResponse(PracticaFinal3.ServiceReference1.getPersonaXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPersonaXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPersonaXMLResult;
        
        public getPersonaXMLResponseBody() {
        }
        
        public getPersonaXMLResponseBody(string getPersonaXMLResult) {
            this.getPersonaXMLResult = getPersonaXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : PracticaFinal3.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<PracticaFinal3.ServiceReference1.WebServiceSoap>, PracticaFinal3.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PracticaFinal3.ServiceReference1.getPersonaXMLResponse PracticaFinal3.ServiceReference1.WebServiceSoap.getPersonaXML(PracticaFinal3.ServiceReference1.getPersonaXMLRequest request) {
            return base.Channel.getPersonaXML(request);
        }
        
        public string getPersonaXML() {
            PracticaFinal3.ServiceReference1.getPersonaXMLRequest inValue = new PracticaFinal3.ServiceReference1.getPersonaXMLRequest();
            inValue.Body = new PracticaFinal3.ServiceReference1.getPersonaXMLRequestBody();
            PracticaFinal3.ServiceReference1.getPersonaXMLResponse retVal = ((PracticaFinal3.ServiceReference1.WebServiceSoap)(this)).getPersonaXML(inValue);
            return retVal.Body.getPersonaXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PracticaFinal3.ServiceReference1.getPersonaXMLResponse> PracticaFinal3.ServiceReference1.WebServiceSoap.getPersonaXMLAsync(PracticaFinal3.ServiceReference1.getPersonaXMLRequest request) {
            return base.Channel.getPersonaXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<PracticaFinal3.ServiceReference1.getPersonaXMLResponse> getPersonaXMLAsync() {
            PracticaFinal3.ServiceReference1.getPersonaXMLRequest inValue = new PracticaFinal3.ServiceReference1.getPersonaXMLRequest();
            inValue.Body = new PracticaFinal3.ServiceReference1.getPersonaXMLRequestBody();
            return ((PracticaFinal3.ServiceReference1.WebServiceSoap)(this)).getPersonaXMLAsync(inValue);
        }
    }
}
